//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividad()
        {
            this.Detalle_Paquete_Turistico = new HashSet<Detalle_Paquete_Turistico>();
        }
    
        public int act_id { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string act_nombre { get; set; }
        [DisplayName("Descripción")]
        [Required]
        public string act_descripcion { get; set; }
        [DisplayName("Costo por Persona")]
        [Required]
        public Nullable<decimal> act_costo { get; set; }
        [DisplayName("Estado")]
        [Required]
        public Nullable<bool> act_estado { get; set; }
        [DisplayName("Foto")]
        
        public string act_ruta_foto_1 { get; set; }
        [DisplayName("Foto")]
        
        public string act_ruta_foto_2 { get; set; }
        public int lug_id { get; set; }

        public HttpPostedFileBase ImagenFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Paquete_Turistico> Detalle_Paquete_Turistico { get; set; }
        public virtual Lugar Lugar { get; set; }
    }
}
