//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Agencia_de_Viajes_CertificacionEntities : DbContext
    {
        public Agencia_de_Viajes_CertificacionEntities()
            : base("name=Agencia_de_Viajes_CertificacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Detalle_Habitacion> Detalle_Habitacion { get; set; }
        public virtual DbSet<Detalle_Paquete_Turistico> Detalle_Paquete_Turistico { get; set; }
        public virtual DbSet<Detalle_Reserva> Detalle_Reserva { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Lugar> Lugar { get; set; }
        public virtual DbSet<Paquete_Turistico> Paquete_Turistico { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Transporte> Transporte { get; set; }
        public virtual DbSet<Viajero> Viajero { get; set; }
    }
}
