//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ciudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ciudad()
        {
            this.Hotel = new HashSet<Hotel>();
            this.Lugar = new HashSet<Lugar>();
        }
    
        public int ciu_id { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string ciu_nombre { get; set; }
        [DisplayName("Decripción")]
        [Required]
        public string ciu_descripcion { get; set; }
        [DisplayName("Clima")]
        [Required]
        public string ciu_clima { get; set; }
        [DisplayName("Recomendaciones")]
        [Required]
        public string ciu_recomendaciones { get; set; }
        [DisplayName("Observaciones")]
        public string ciu_observacion { get; set; }
        [DisplayName("Foto")]
        public string ciu_ruta_foto { get; set; }

        public HttpPostedFileBase ImagenFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lugar> Lugar { get; set; }
    }
}
