//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int cli_id { get; set; }
        public string cli_cedula { get; set; }
        public string cli_nombre1 { get; set; }
        public string cli_nombre2 { get; set; }
        public string cli_apellido1 { get; set; }
        public string cli_apellido2 { get; set; }
        public Nullable<System.DateTime> cli_fecha_nac { get; set; }
        public string cli_email { get; set; }
        public string cli_direccion { get; set; }
        public string cli_telefono { get; set; }
        public string cli_observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
