//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detalle_Reserva()
        {
            this.Viajero = new HashSet<Viajero>();
        }
    
        public int dres_id { get; set; }
        public int res_id { get; set; }
        public int ptu_id { get; set; }
        public Nullable<decimal> dres_costo { get; set; }
        public Nullable<decimal> dres_total { get; set; }
        public Nullable<bool> dres_estado { get; set; }
        public string dres_observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viajero> Viajero { get; set; }
        public virtual Paquete_Turistico Paquete_Turistico { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
