//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Detalle_Habitacion = new HashSet<Detalle_Habitacion>();
        }
    
        public int hot_id { get; set; }
        
        public int ciu_id { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string hot_nombre { get; set; }
        [DisplayName("Dirección")]
        [Required]
        public string hot_direccion { get; set; }
        [DisplayName("Calificación")]
        [Required]
        public Nullable<int> hot_calificacion { get; set; }
        [DisplayName("Dispone Desayuno")]
        [Required]
        public Nullable<bool> hab_desayuno { get; set; }
        [DisplayName("Telefono")]
        [Required]
        public string hot_telefono { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Habitacion> Detalle_Habitacion { get; set; }
    }
}
