//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Paquete_Turistico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquete_Turistico()
        {
            this.Detalle_Paquete_Turistico = new HashSet<Detalle_Paquete_Turistico>();
            this.Detalle_Reserva = new HashSet<Detalle_Reserva>();
        }

        public int ptu_id { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string ptu_nombre { get; set; }
        [DisplayName("Descripción")]
        [Required]
        public string ptu_descripcion { get; set; }
        [DisplayName("Estado")]
        [Required]
        public Nullable<bool> ptu_estado { get; set; }
        [DisplayName("Foto")]
        public byte[] ptu_foto_1 { get; set; }
        [DisplayName("Foto")]
        public byte[] ptu_foto_2 { get; set; }
        [DisplayName("Fecha Salida")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public Nullable<System.DateTime> ptu_fecha_salida { get; set; }
        [DisplayName("Fecha Llegada")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public Nullable<System.DateTime> ptu_fecha_llegada { get; set; }
        public int dha_id { get; set; }

        public HttpPostedFileBase ImagenFile { get; set; }

        public virtual Detalle_Habitacion Detalle_Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Paquete_Turistico> Detalle_Paquete_Turistico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Reserva> Detalle_Reserva { get; set; }
    }
}
