//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pry_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viajero
    {
        public int via_id { get; set; }
        public int dres_id { get; set; }
        public string via_cedula { get; set; }
        public string via_nombre1 { get; set; }
        public string via_nombre2 { get; set; }
        public string via_apellido1 { get; set; }
        public string via_apellido2 { get; set; }
        public Nullable<System.DateTime> via_fecha_nac { get; set; }
        public string via_tipo_sangre { get; set; }
        public string via_email { get; set; }
        public string via_direccion { get; set; }
        public string via_telefono { get; set; }
        public string via_pais { get; set; }
        public string via_nacionalidad { get; set; }
        public string via_observacion { get; set; }
    
        public virtual Detalle_Reserva Detalle_Reserva { get; set; }
    }
}
